# ADOS Default Configuration
# Phase 1-3.1 System Configuration

system:
  name: "ADOS - Autonomous Development Operations System"
  version: "1.0.0"
  environment: "development"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "ados_orchestrator.log"
  max_size: "10MB"
  backup_count: 5

orchestrator:
  max_concurrent_tasks: 5
  task_timeout: 300  # seconds
  retry_attempts: 3
  heartbeat_interval: 30

crews:
  orchestrator:
    max_agents: 5
    execution_timeout: 600
    memory_limit: "1GB"
  
  research:
    max_agents: 3
    execution_timeout: 300
    memory_limit: "512MB"
  
  development:
    max_agents: 4
    execution_timeout: 900
    memory_limit: "1GB"

memory:
  persistence: true
  backend: "file"
  storage_path: "memory/data"
  cleanup_interval: 3600  # seconds
  max_storage_size: "100MB"

tasks:
  default_priority: "medium"
  decomposition_depth: 3
  parallel_execution: true
  dependency_resolution: true

agents:
  default_model: "gpt-4"
  temperature: 0.7
  max_tokens: 2000
  timeout: 120

performance:
  monitoring_enabled: true
  metrics_collection: true
  profiling: false
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 85
    task_failure_rate: 10

security:
  sandbox_enabled: true
  resource_limits: true
  code_validation: true
  audit_logging: true